title: Frances Grace Hart
logo: /assets/images/FrancesGHartCrop.png
description: 
  name: Grace Hart
  pronouns: she/her
  education:
    - status: undergraduate psychology student
      school: Boston College
      graduation: December 2023
  future_plans:
    - pursue a PhD in clinical psychology
    - use computational modeling to improve our understanding of the relationship between suicide, death attitudes, and eudaemonic wellbeing
  labs:
    - name: Cognition and Affect Research and Education Lab
      location: McLean Hospital
    - name: Belief Lab
      location: Yale School of Medicine
      email: https://belieflab.yale.edu
  hobbies:
    - reading
    - practicing yoga
show_downloads: true
google_analytics: true
theme: jekyll-theme-minimal
twitter: https://twitter.com/francesghart
cv: /assets/documents/HartJuly2023CV.pdf
banner: /assets/images/DanseMacabreCrop.png
github: https://github.com/hartfa
#description: Hello! My name is Grace Hart (she/her) and I am an undergraduate psychology student at Boston College graduating in December 2023. I hope to pursue a PhD in clinical psychology, where I would like to use computational modeling to improve our understanding of the relationship between suicide, death attitudes, and eudaemonic wellbeing. I am currently completing an Honors Thesis in the Cognition and Affect Research and Education Lab at McLean Hospital, and recently began as an intern in the Belief Lab at Yale School of Medicine. In my free time, I enjoy reading and practicing yoga.
